---
name: Docker Image Build
on:
  push:
    branches: main
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set ENVs
        run: |
          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
            echo "APP_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
          else
            echo "APP_VERSION=latest" >> $GITHUB_ENV
            echo "BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: stvasyl/echo-server:${{ env.APP_VERSION }}
          build-args: |
            GIT_BRANCH: ${{ env.BRANCH }}
            GIT_HASH: ${{ github.sha }}
            APP_VERSION: ${{ env.APP_VERSION }}
